Repository algosup/2024-2025-project-4-web-fpga-team-4, pull requests merged in 2025-03, with the labels that each got.

#17 Formatting file convention + unit test preview
  .gitignore
  documents/quality-assurance/note.md
  documents/quality-assurance/test-plan.md
  documents/technical-specifications/naming-conventions.md
  src/test/logs/2025-03-12-unit-test-html-css.json
  src/test/logs/2025-03-13-unit-test-html-css.json
  src/test/logs/2025-03-14-unit-test-html-css.json
  src/test/package-lock.json
  src/test/unit-test-html-css.ts
Labels: enhancement

#20 Putting Management documents into the main branch
  documents/management/communication/communication-artifact.md
  documents/management/management-artifact.md
  documents/management/post-mortem.md
  documents/management/weekly-report/images/kpis-week2.png
  documents/management/weekly-report/images/kpis-week3.png
  documents/management/weekly-report/images/kpis-week4.png
  documents/management/weekly-report/weekly-report1.md
  documents/management/weekly-report/weekly-report2.md
  documents/management/weekly-report/weekly-report3.md
  documents/management/weekly-report/weekly-report4.md
  documents/management/weekly-report/weekly-report5.md
  documents/management/weekly-report/weekly-report6.md
  documents/management/weekly-report/weekly-reports-cumulative.md
Labels: documentation

#24 Technical specifications
  documents/technical-specifications/images/animations/animations-example-ids.png
  documents/technical-specifications/images/animations/animations-example-path-1.png
  documents/technical-specifications/images/animations/animations-example-path-2.png
  documents/technical-specifications/images/animations/animations-example-path-3.png
  documents/technical-specifications/images/animations/animations-example.png
  documents/technical-specifications/images/async-reset-example.png
  documents/technical-specifications/images/clock-example.png
  documents/technical-specifications/images/connection-example.png
  documents/technical-specifications/images/dataview-trigger.png
  documents/technical-specifications/images/dff-example.png
  documents/technical-specifications/images/download-button.png
  documents/technical-specifications/images/element-design.png
  documents/technical-specifications/images/first-button.png
  documents/technical-specifications/images/hide-button.png
  documents/technical-specifications/images/import-button.png
  documents/technical-specifications/images/last-button.png
  documents/technical-specifications/images/lut-example.png
  documents/technical-specifications/images/next-button.png
  documents/technical-specifications/images/pause-button.png
  documents/technical-specifications/images/play-button.png
  documents/technical-specifications/images/previous-button.png
  documents/technical-specifications/images/settings-button.png
  documents/technical-specifications/images/speed-display.png
  documents/technical-specifications/images/speed-down-button.png
  documents/technical-specifications/images/speed-up-button.png
  documents/technical-specifications/images/theme-button.png
  documents/technical-specifications/images/user-input-example.png
  documents/technical-specifications/images/user-output-example.png
  documents/technical-specifications/images/zoom-display.png
  documents/technical-specifications/images/zoom-down-button.png
  documents/technical-specifications/images/zoom-up-button.png
  documents/technical-specifications/naming-conventions.md
  documents/technical-specifications/technical-specifications.md
Labels: documentation, enhancement, review

#26 Fixing Technical Specifications formatting issues
  documents/technical-specifications/technical-specifications.md
Labels: documentation
